-- Khamron Kannapel
-- M04 Midterm
-- 9/12/2022

CREATE TABLE CUSTOMERS(
	CUSTOMER_ID 	NUMBER(10),
	LAST_NAME		VARCHAR2(25),
	FIRST_NAME		VARCHAR2(25),
	HOME_PHONE		VARCHAR2(12),
	ADDRESS			VARCHAR2(100),
	CITY			VARCHAR2(30),
	STATE			VARCHAR2(2),
	EMAIL			VARCHAR2(25),
	CELL_PHONE		VARCHAR2(12)
);

CREATE TABLE MOVIES(
	TITLE_ID		NUMBER(10),
	TITLE			VARCHAR2(60),
	DESCRIPTION		VARCHAR2(400),
	RATING			VARCHAR2(4),
	CATEGORY		VARCHAR2(20),
	RELEASE_DATE	DATE
);

CREATE TABLE MEDIA(
	MEDIA_ID		NUMBER(10),
	FORMAT			VARCHAR2(3),
	TITLE_ID		NUMBER(10)
);

CREATE TABLE RENTAL_HISTORY(
	MEDIA_ID		NUMBER(10),
	RENTAL_DATE		DATE,
	CUSTOMER_ID		NUMBER(10),
	RETURN_DATE		DATE
);

CREATE TABLE ACTORS(
	ACTOR_ID		NUMBER(10),
	STAGE_NAME		VARCHAR2(40),
	FIRST_NAME		VARCHAR2(25),
	LAST_NAME		VARCHAR2(25),
	BIRTH_DATE		DATE
);

CREATE TABLE STAR_BILLINGS(
	ACTOR_ID		NUMBER(10),
	TITLE_ID		NUMBER(10),
	"COMMENT"		VARCHAR2(40)
);




ALTER TABLE CUSTOMERS ADD CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID);

ALTER TABLE MOVIES ADD CONSTRAINT PK_MOVIES PRIMARY KEY (TITLE_ID);

ALTER TABLE MEDIA ADD CONSTRAINT PK_MEDIA PRIMARY KEY (MEDIA_ID);

ALTER TABLE RENTAL_HISTORY ADD CONSTRAINT PK_FK_RENTAL_HISTORY PRIMARY KEY (MEDIA_ID, RENTAL_DATE);

ALTER TABLE ACTORS ADD CONSTRAINT PK_ACTORS PRIMARY KEY (ACTOR_ID);

ALTER TABLE STAR_BILLINGS ADD CONSTRAINT PK_STAR_BILLINGS PRIMARY KEY (ACTOR_ID, TITLE_ID);



ALTER TABLE MEDIA ADD CONSTRAINT FK_MEDIA_MOVIES FOREIGN KEY (TITLE_ID)
	REFERENCES MOVIES (TITLE_ID);
	
ALTER TABLE RENTAL_HISTORY ADD CONSTRAINT FK_RENT_MEDIA FOREIGN KEY (MEDIA_ID)
	REFERENCES MEDIA (MEDIA_ID);
	
ALTER TABLE RENTAL_HISTORY ADD CONSTRAINT FK_RENT_CUST FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMERS (CUSTOMER_ID);


ALTER TABLE MOVIES
ADD CONSTRAINT CHK_RATING CHECK (RATING='G' OR RATING='PG' OR RATING='R' OR RATING='PG13');

ALTER TABLE MOVIES
ADD CONSTRAINT CHK_CATEGORY CHECK (CATEGORY='DRAMA' OR CATEGORY='COMEDY' OR CATEGORY='ACTION' OR CATEGORY='CHILD' OR CATEGORY='SCIFI' OR CATEGORY='DOCUMENTARY');



/*
CREATE TABLE STAR_BILLINGS(
	ACTOR_ID	NUMBER(10),
	TITLE_ID	NUMBER(10),
	COMMENTS	VARCHAR2(40),
	CONSTRAINT PK_ACTOR_ID PRIMARY KEY (ACTOR_ID),
	CONSTRAINT PK_TITLE_ID PRIMARY KEY (TITLE_ID);
);
*/
