-- Khamron Kannapel
-- M08 Final Project
-- 10/10/2022

CREATE VIEW [TITLE_UNAVAIL] AS
SELECT MOVIES.TITLE, RENTAL_HISTORY.MEDIA_ID
FROM MOVIES
INNER JOIN MEDIA
ON MOVIES.TITLE_ID = MEDIA.TITLE_ID
INNER JOIN RENTAL_HISTORY
ON RENTAL_HISTORY.MEDIA_ID = MEDIA.MEDIA_ID
WHERE RETURN_DATE = NULL;


CREATE SEQUENCE CUSTOMER_ID_SEQ
START WITH 101
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE TITLE_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE MEDIA_ID_SEQ
START WITH 92
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE ACTOR_ID_SEQ
START WITH 1001
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE INDEX INDEX_LAST_NAME
ON CUSTOMERS(LAST_NAME);


CREATE SYNONYM TU
FOR TITLE_UNAVAIL;

